name: tcc
description: "TCC - State Management"
publish_to: 'none'
version: 1.0.0+1

workspace:
  - modules/common
  - modules/dependencies
  - modules/home
  - modules/task

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  common:
    path: ./modules/common
  dependencies:
    path: ./modules/dependencies
  home:
    path: ./modules/home
  task:
    path: ./modules/task

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true