name: task
description: "Todo module with To-Do List features"
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.13.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  common:
    path: ../common
  dependencies:
    path: ../dependencies